# Generated by Django 2.2.6 on 2019-10-04 08:36

from django.db import migrations, models
import e_signatures.services


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('image', models.ImageField(upload_to=e_signatures.services.signature_image_path)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
