# Generated by Django 2.2.6 on 2019-10-05 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_signatures', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signatures',
            new_name='Signature',
        ),
    ]
