# Generated by Django 3.0.7 on 2020-06-17 11:53

from django.db import migrations, models
import e_signatures.services


class Migration(migrations.Migration):

    dependencies = [
        ('e_signatures', '0002_auto_20191005_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='image_no_required',
            field=models.ImageField(blank=True, null=True, upload_to=e_signatures.services.signature_image_path),
        ),
    ]
